sonar.projectKey=kalhara-ediriweera_user-service1
sonar.organization=kalhara-ediriweera

# exclude tests from source
sonar.sources=src
sonar.exclusions=src/tests/**

# define tests separately
sonar.tests=src/tests

sonar.sourceEncoding=UTF-8